-- Atlas Arcade: competitive-time leaderboards and optional cloud progress
-- Run this file once in the Supabase SQL Editor for your project.

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

-- One best 197-country competitive time per player, mode, and rules version.
-- player_key is a one-way hash of the browser identity (or signed-in user ID),
-- so the private identity token is never exposed by the public leaderboard.
create table if not exists public.atlas_sprint_scores (
  id bigint generated by default as identity primary key,
  sprint_version smallint not null,
  mode text not null check (mode in ('locate', 'capitals', 'flags', 'reverse', 'mixed', 'spelling')),
  player_key text not null,
  auth_user_id uuid null references auth.users(id) on delete set null,
  player_name text not null check (char_length(player_name) between 2 and 24),
  elapsed_ms integer not null check (elapsed_ms between 15000 and 86400000),
  mistakes integer not null check (mistakes between 0 and 5000),
  official_ms integer generated always as (elapsed_ms + mistakes * 2000) stored,
  completed_count smallint not null check (completed_count = 197),
  created_at timestamptz not null default timezone('utc', now()),
  last_submission_at timestamptz not null default timezone('utc', now()),
  constraint atlas_sprint_scores_player_mode_key unique (sprint_version, mode, player_key)
);

create index if not exists atlas_sprint_scores_rank_idx
  on public.atlas_sprint_scores (sprint_version, mode, official_ms, mistakes, elapsed_ms, created_at);

alter table public.atlas_sprint_scores enable row level security;

drop policy if exists "Public can read sprint records" on public.atlas_sprint_scores;
drop policy if exists "Public can read competitive records" on public.atlas_sprint_scores;
create policy "Public can read competitive records"
  on public.atlas_sprint_scores
  for select
  to anon, authenticated
  using (true);

-- Direct writes are intentionally not granted. All submissions pass through
-- the validation function below.
revoke all on public.atlas_sprint_scores from anon, authenticated;
grant select (sprint_version, mode, player_name, elapsed_ms, mistakes, official_ms, created_at)
  on public.atlas_sprint_scores to anon, authenticated;

create or replace function public.submit_atlas_sprint(
  p_sprint_version integer,
  p_mode text,
  p_player_id text,
  p_player_name text,
  p_elapsed_ms integer,
  p_mistakes integer,
  p_completed_count integer
)
returns table(saved boolean, world_rank bigint, official_ms integer)
language plpgsql
security definer
set search_path = public, auth, extensions
as $$
declare
  v_identity text;
  v_player_key text;
  v_name text;
  v_auth_user uuid := auth.uid();
  v_official integer;
  v_existing public.atlas_sprint_scores%rowtype;
  v_saved boolean := false;
  v_rank_official integer;
  v_rank_mistakes integer;
  v_rank_elapsed integer;
  v_rank_created timestamptz;
begin
  if p_sprint_version <> 1 then
    raise exception 'Unsupported competitive rules version';
  end if;

  if p_mode not in ('locate', 'capitals', 'flags', 'reverse', 'mixed', 'spelling') then
    raise exception 'Unsupported competitive mode';
  end if;

  if p_completed_count <> 197 then
    raise exception 'A competitive game must include all 197 countries';
  end if;

  if p_elapsed_ms is null or p_elapsed_ms < 15000 or p_elapsed_ms > 86400000 then
    raise exception 'Elapsed time is outside the accepted range';
  end if;

  if p_mistakes is null or p_mistakes < 0 or p_mistakes > 5000 then
    raise exception 'Mistake count is outside the accepted range';
  end if;

  v_name := btrim(regexp_replace(coalesce(p_player_name, ''), '[^[:alnum:] _-]+', '', 'g'));
  v_name := regexp_replace(v_name, '[[:space:]]+', ' ', 'g');
  if char_length(v_name) < 2 or char_length(v_name) > 24 then
    raise exception 'Display name must contain 2 to 24 supported characters';
  end if;

  if v_auth_user is not null then
    v_identity := 'account:' || v_auth_user::text;
  else
    if p_player_id is null or char_length(p_player_id) < 20 or char_length(p_player_id) > 96 then
      raise exception 'Missing or invalid browser identity';
    end if;
    v_identity := 'guest:' || p_player_id;
  end if;

  v_player_key := encode(digest(v_identity, 'sha256'), 'hex');
  v_official := p_elapsed_ms + p_mistakes * 2000;

  -- Serialize submissions for the same hidden identity and mode.
  perform pg_advisory_xact_lock(hashtextextended(v_player_key || ':' || p_mode || ':' || p_sprint_version::text, 0));

  select *
    into v_existing
    from public.atlas_sprint_scores
   where sprint_version = p_sprint_version
     and mode = p_mode
     and player_key = v_player_key
   for update;

  if found and v_existing.last_submission_at > timezone('utc', now()) - interval '2 seconds' then
    raise exception 'Please wait before submitting again';
  end if;

  if not found then
    insert into public.atlas_sprint_scores (
      sprint_version, mode, player_key, auth_user_id, player_name,
      elapsed_ms, mistakes, completed_count, created_at, last_submission_at
    ) values (
      p_sprint_version, p_mode, v_player_key, v_auth_user, v_name,
      p_elapsed_ms, p_mistakes, p_completed_count,
      timezone('utc', now()), timezone('utc', now())
    );
    v_saved := true;
    v_rank_official := v_official;
    v_rank_mistakes := p_mistakes;
    v_rank_elapsed := p_elapsed_ms;
    v_rank_created := timezone('utc', now());
  elsif (v_official, p_mistakes, p_elapsed_ms) <
        (v_existing.official_ms, v_existing.mistakes, v_existing.elapsed_ms) then
    update public.atlas_sprint_scores
       set auth_user_id = v_auth_user,
           player_name = v_name,
           elapsed_ms = p_elapsed_ms,
           mistakes = p_mistakes,
           completed_count = p_completed_count,
           created_at = timezone('utc', now()),
           last_submission_at = timezone('utc', now())
     where id = v_existing.id;
    v_saved := true;
    v_rank_official := v_official;
    v_rank_mistakes := p_mistakes;
    v_rank_elapsed := p_elapsed_ms;
    v_rank_created := timezone('utc', now());
  else
    v_rank_official := v_existing.official_ms;
    v_rank_mistakes := v_existing.mistakes;
    v_rank_elapsed := v_existing.elapsed_ms;
    v_rank_created := v_existing.created_at;
    update public.atlas_sprint_scores
       set player_name = v_name,
           auth_user_id = coalesce(v_auth_user, auth_user_id),
           last_submission_at = timezone('utc', now())
     where id = v_existing.id;
  end if;

  return query
  select
    v_saved,
    1 + count(*)::bigint,
    v_rank_official
  from public.atlas_sprint_scores s
  where s.sprint_version = p_sprint_version
    and s.mode = p_mode
    and (s.official_ms, s.mistakes, s.elapsed_ms, s.created_at) <
        (v_rank_official, v_rank_mistakes, v_rank_elapsed, v_rank_created);
end;
$$;

revoke all on function public.submit_atlas_sprint(integer, text, text, text, integer, integer, integer) from public;
grant execute on function public.submit_atlas_sprint(integer, text, text, text, integer, integer, integer)
  to anon, authenticated;

-- Private account-owned progress. Guests continue to use localStorage only.
create table if not exists public.atlas_player_progress (
  user_id uuid primary key references auth.users(id) on delete cascade,
  player_name text not null default 'Explorer' check (char_length(player_name) between 2 and 24),
  progress jsonb not null default '{}'::jsonb check (jsonb_typeof(progress) = 'object' and octet_length(progress::text) <= 2000000),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.atlas_player_progress enable row level security;

drop policy if exists "Players can read their own progress" on public.atlas_player_progress;
create policy "Players can read their own progress"
  on public.atlas_player_progress for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Players can create their own progress" on public.atlas_player_progress;
create policy "Players can create their own progress"
  on public.atlas_player_progress for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Players can update their own progress" on public.atlas_player_progress;
create policy "Players can update their own progress"
  on public.atlas_player_progress for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Players can delete their own progress" on public.atlas_player_progress;
create policy "Players can delete their own progress"
  on public.atlas_player_progress for delete to authenticated
  using (auth.uid() = user_id);

revoke all on public.atlas_player_progress from anon;
grant select, insert, update, delete on public.atlas_player_progress to authenticated;
